Technical Lab: This lab focuses on using NumPy to vectorise. 

In [1]:
# Imports
import numpy as np
import time 

### Vectors

In [6]:
# An array of 4 zeros (floats)
a = np.zeros(4); print(f"np.zeros(4) :   a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
# An array of 4 zeros (floats)
a = np.zeros((4,)); print(f"np.zeros((4,)) :   a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
# An array of 4 random floats between 0 and 1
a = np.random.random_sample(4); print(f"np.random.random_sample(4) :   a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
# An array of numbers 0 - 3
a = np.arange(4.); print(f"np.arange(4.):     a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
# An array of 4 random floats between 0 and 1
a = np.random.rand(4); print(f"np.random.rand(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
# An array of 4 assigned integers
a = np.array([5,4,3,2]);  print(f"np.array([5,4,3,2]):  a = {a},     a shape = {a.shape}, a data type = {a.dtype}")
# An array of 4 assigned floats
a = np.array([5.,4,3,2]); print(f"np.array([5.,4,3,2]): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.zeros(4) :   a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.zeros((4,)) :   a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.random.random_sample(4) :   a = [0.50991515 0.68754749 0.11362279 0.6025375 ], a shape = (4,), a data type = float64
np.arange(4.):     a = [0. 1. 2. 3.], a shape = (4,), a data type = float64
np.random.rand(4): a = [0.58826574 0.84296888 0.13031442 0.42443888], a shape = (4,), a data type = float64
np.array([5,4,3,2]):  a = [5 4 3 2],     a shape = (4,), a data type = int64
np.array([5.,4,3,2]): a = [5. 4. 3. 2.], a shape = (4,), a data type = float64


### Indexing

In [7]:
# 1D vectors indexing practice
a = np.arange(10) #0-9
print(a)

# Accessing an element
print(f"a[2].shape: {a[2].shape} a[2] = {a[2]}, Accessing an element returns a scalar")

# Accessing the last element 
print(f"a[-1] = {a[-1]}")

# Indexing must be within range
try: 
    c = a[10] #out of range
except Exception as e: 
    print("The error message you'll see is:")
    print(e)

[0 1 2 3 4 5 6 7 8 9]
a[2].shape: () a[2] = 2, Accessing an element returns a scalar
a[-1] = 9
The error message you'll see is:
index 10 is out of bounds for axis 0 with size 10


### Slicing

In [8]:
# 1D Vector slicing practice
# Use a from previous exercise 

# Access 5 consecutive elements (start:stop:step)
c = a[2:7:1];     print("a[2:7:1] = ", c)

# Access 3 elements seperated by two
c = a[2:7:2];     print("a[2:7:2] = ", c)

# Access all elements index 3 and above
c = a[3:];     print("a[3:] = ", c)

# Access all elements below index 3 (excl.)
c = a[:3];     print("a[:3] = ", c)

# Access all elements
c = a[:];     print("a[:] = ", c)

a[2:7:1] =  [2 3 4 5 6]
a[2:7:2] =  [2 4 6]
a[3:] =  [3 4 5 6 7 8 9]
a[:3] =  [0 1 2]
a[:] =  [0 1 2 3 4 5 6 7 8 9]


### Single Vector Operations

In [10]:
# Sample
a = np.arange(4)
print(f"a              : {a}")

# Negate a
b = -a
print(f"b = -a         : {b}")

# Sum all elements of a 
b = np.sum(a)
print(f"b = np.sum(a)  : {b}")

# Find the mean of a
b = np.mean(a)
print(f"b = np.mean(a) : {b}")

# Square each element of a
b = a ** 2
print(f"b = a**2       : {b}")

a              : [0 1 2 3]
b = -a         : [ 0 -1 -2 -3]
b = np.sum(a)  : 6
b = np.mean(a) : 1.5
b = a**2       : [0 1 4 9]


## Matrices

In [11]:
# Creating 
a = np.zeros((1,5))  # (down, side) (y, x) (rows, columns)
print(f"a shape = {a.shape}, a = {a}")  

a = np.zeros((2,1))
print(f"a shape = {a.shape}, a = {a}")  

a = np.random.random_sample((1,1))
print(f"a shape = {a.shape}, a = {a}")  

a shape = (1, 5), a = [[0. 0. 0. 0. 0.]]
a shape = (2, 1), a = [[0.]
 [0.]]
a shape = (1, 1), a = [[0.51967755]]


### Indexing

In [20]:
# Reshaping a 1D into a 2D
a = np.arange(6).reshape(-1,2) #the -1 acts a way saying "dont care how many rows, just two columns"
print(f"a.shape: {a.shape}, \na= {a}")

# Accessing an element
print(f"a[2,0] = {a[2, 0]},    type(a[2,0]) = {type(a[2, 0])} Accessing an element returns a scalar\n")

# Accessing a row
print(f"a[2] = {a[2]},    type(a[2]) = {type(a[2])} Accessing a row returns an array\n")

SyntaxError: f-string: invalid syntax (2733674934.py, line 11)

### Slicing

In [22]:
# 2D slicing operations
a = np.arange(20).reshape(-1, 10)
print(f"a = \n{a}")

# Accessing 5 consecutive elements (start:stop:step)
print("a[0, 2:7:1] = ", a[0, 2:7:1], ",  a[0, 2:7:1].shape =", a[0, 2:7:1].shape, "a 1-D array")

# Accessing 5 consecutive elements (start:stop:step) in two rows
print("a[:, 2:7:1] = ", a[:, 2:7:1], ",  a[:, 2:7:1].shape =", a[:, 2:7:1].shape, "a 2-D array")

# Accessing all elements
print("a[:,:] = ", a[:,:], ",  a[:,:].shape =", a[:,:].shape)

# Accessing all elements in one row
print("a[1,:] = ", a[1,:], ",  a[1,:].shape =", a[1,:].shape, "a 1-D array")
print("a[1]   = ", a[1],   ",  a[1].shape   =", a[1].shape, "a 1-D array")

a = 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
a[0, 2:7:1] =  [2 3 4 5 6] ,  a[0, 2:7:1].shape = (5,) a 1-D array
a[:, 2:7:1] =  [[ 2  3  4  5  6]
 [12 13 14 15 16]] ,  a[:, 2:7:1].shape = (2, 5) a 2-D array
a[:,:] =  [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] ,  a[:,:].shape = (2, 10)
a[1,:] =  [10 11 12 13 14 15 16 17 18 19] ,  a[1,:].shape = (10,) a 1-D array
a[1]   =  [10 11 12 13 14 15 16 17 18 19] ,  a[1].shape   = (10,) a 1-D array
